source 'http://rubygems.org'

gem 'haml'
gem 'sass'
gem 'rails', '3.0.7'
gem 'mysql'
gem 'devise', '1.3.4'
gem 'pickler'
gem 'decent_exposure'
gem 'dynamic_form'

group :development, :test do
  gem 'capybara'
  gem 'cucumber-rails'
  gem 'database_cleaner'
  gem 'fabrication'
  gem 'fuubar'
  gem 'fuubar-cucumber'
  gem 'itslog'
  gem 'rspec-rails'
  gem 'ruby-debug19', require: 'ruby-debug'
  gem 'thin'
  gem 'email_spec'
  gem 'launchy'
  gem 'shoulda'
end
