source 'http://rubygems.org'

gem 'bson_ext'
gem 'decent_exposure'
gem 'devise', '1.3.4'
gem 'haml-rails'
gem 'mongoid'
gem 'sass'
gem 'rails', '3.0.7'
gem 'sqlite3'

group :development, :test do
  gem 'capybara'
  gem 'cucumber-rails'
  gem 'database_cleaner'
  gem 'fabrication'
  gem 'ffaker'
  gem 'fuubar'
  gem 'fuubar-cucumber'
  gem 'itslog'
  gem 'launchy'
  gem 'pickler'
  gem 'rspec-rails'
  gem 'ruby-debug19', require: 'ruby-debug'
  gem 'thin'
end
