source 'http://rubygems.org'

gem 'devise'
gem 'haml'
gem 'mysql2', '0.2.7'
gem 'sass'
gem 'rails', '3.0.7'
gem 'sqlite3'

group :development, :test do
  gem 'engineyard'
  gem 'capybara'
  gem 'cucumber-rails'
  gem 'database_cleaner'
  gem 'fabrication'
  gem 'fuubar'
  gem 'fuubar-cucumber'
  gem 'hpricot'
  gem 'itslog'
  gem 'launchy'
  gem 'pickler'
  gem 'rspec-rails'
  gem 'ruby-debug19', require: 'ruby-debug'
  gem 'ruby_parser'
  gem 'shoulda'
  gem 'thin'
end
